### ISSUE TITLE
[Request] Adaptive Menu Position

### ISSUE THREAD

**Issue by Aerinx** [JustBoorish/BooBuilds#1]
Could you add the same feature as BooSprint where if you position the button on the bottom side the menu pops upwards instead of downwards? Right now the menu goes offscreen and you can't click on some options.

**Comment by JustBoorish** [comment]
This is already done in my development version and will be part of the 1.9 release.

**Comment by Aerinx** [comment]
I read the first answer on my mail and I was ready to check versions, erase and do clean install, trying to troubleshoot it on my end... Thank god I read this first 😆 

Thank you, it's awesome that you changed it, can't wait for the next version, I found a great spot for the button near the skills bar 😄
