### ISSUE TITLE
[Feature] Button for Outfits

### ISSUE THREAD

**Issue by Aerinx** [JustBoorish/BooBuilds#2]
An optional button to open the outfits menu instead of using Shift+Left Click would be great, shift isn't used for anything in the game afaik and as such it is not a key that I have assigned in my gaming keyboard. It is also very bothersome because it's not something I use often enough to develop muscle memory for it, but I use it enough to be annoying not being to change outfits quickly.

Thank you for your time and this magnificent mod.

**Comment by JustBoorish** [comment]
I don't really want to add a second icon, but I can change it so that right click shows the outfit selector and shift+left click shows the build/outfit edit window.

**Comment by Aerinx** [comment]
I like that idea even more than a second button, I had not thought of that.

**Comment by JustBoorish** [comment]
Available in version 1.9
